---
# This script contains commands to build react applications from docroot/reactapps folder.

- name: Current site url
  debug:
    var: site_url

- name: Set environment variables
  lineinfile:
    line: 'REACT_APP_API_URL="{{ site_url }}"'
    dest: 'reactapps/prgreg/.env.local'
    create: 'yes'
  sudo: yes

- name: Install dependencies
  shell: cd reactapps/prgreg && yarn install
  sudo: yes

- name: Build application
  shell: cd reactapps/prgreg && yarn build
  sudo: yes

- name: Build storybook
  shell: cd reactapps/prgreg && yarn storybook-build
  sudo: yes