---
# This script contains commands to manage "shell commands":
# - Running registry rebuild (when modules have been moved to new directory)
# - Running database updates

- name: Run shell commands
  sudo: yes
  shell: "{{ item.arguments }}"
  when: item.status == true
  with_items: env.shell_commands

# Update database.
- name: Updating database
  sudo: yes
  shell: "{{ php_env_vars }} drush -dvy updb -l {{ site_url }}"
