---
# This playbook should be executed using reinstall.sh script
# Developed for ansible version >= 1.7
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    config_folder: 'vars'

  vars_files:
    - devops/reinstall/{{ config_folder }}/global_settings.yml
    - devops/reinstall/{{ config_folder }}/environments/global_env.yml

  tasks:
  - name: Include specific variables per environment
    include_vars: "devops/reinstall/{{ config_folder }}/environments/{{ pp_environment }}_env.yml"
    tags: [ 'settings', 'pre-settings', 'post-settings', 'modules-enable', 'drush-commands' , 'shell-commands', 'pre-drush-commands' ]

  - include: devops/reinstall/database_backup.yml
    when: make_backup
    tags: [ 'database-backup' ]

  - include: devops/reinstall/prepare_environment.yml
    tags: [ 'prepare-environment' ]

  - include: devops/reinstall/old_source_sql_workflow.yml
    when: (workflow_type == "profile" or workflow_type == "sql") and old_site_db
    tags: [ 'profile-workflow', 'sql-workflow', 'prepare-environment' ]

  - include: devops/reinstall/pre_settings.yml
    when: workflow_type == "sql" or not run_installation_process or run_installation_process == 'false'
    tags: [ 'settings', 'pre-settings', 'sql-workflow' ]

  - include: devops/reinstall/sql_workflow.yml
    when: workflow_type == "sql" and not docker_sql
    tags: [ 'sql-workflow' ]

  - include: devops/reinstall/docker_sql_workflow.yml
    when: workflow_type == "sql" and docker_sql
    tags: [ 'sql-workflow' ]

  - include: devops/reinstall/pre_drush_commands.yml
    tags: [ 'drush-commands', 'pre-drush-commands' ]

  - include: devops/reinstall/shell_commands.yml
    when: workflow_type == "sql"
    tags: [ 'sql-workflow', 'shell-commands']

  - include: devops/reinstall/profile_workflow.yml
    when: workflow_type == "profile"
    tags: [ 'profile-workflow' ]

  - include: devops/reinstall/prepare_environment.yml
    tags: [ 'prepare-environment' ]

  - include: devops/reinstall/post_settings.yml
    tags: [ 'settings', 'post-settings' ]

  - include: devops/reinstall/modules_enable.yml
    tags: [ 'modules-enable' ]
    when: run_installation_process

  - include: devops/reinstall/drush_commands.yml
    tags: [ 'drush-commands' ]
    when: run_installation_process

  - include: devops/reinstall/reactapps.yml
    tags: [ 'react-commands' ]
    when: reactapps
